version: '1'

services:
  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password -h 127.0.0.1
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wldt-db
      MYSQL_USER: user_name
      MYSQL_PASSWORD: root_password
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80


volumes:
  dbdata: